version: '3.3'
services:
  postgres:
    image: ${DOCKER_IMAGE_PREFIX}postgres:16.4-alpine
    container_name: nestjs-production-ready-starter-integration-test-postgres
    ports:
      - 5498:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_db
    volumes:
      - ../local/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
